image: tiangolo/docker-with-compose

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - deploy

build-prod:
  stage: build
  script:
    - docker-compose build --build-arg RAILS_MASTER_KEY=$RAILS_MASTER_KEY
  only:
    - main
  tags:
    - prod

deploy-traefik:
  stage: deploy
  script:
    - docker swarm init --default-addr-pool 10.20.0.0/16
    - docker network create --driver=overlay traefik-public
    - export NODE_ID=$(docker info -f '{{.Swarm.NodeID}}')
    - docker node update --label-add traefik-public.traefik-public-certificates=true $NODE_ID
    - docker stack deploy -c traefik.yml traefik
  only:
    - traefik
  tags:
    - prod

deploy-prod:
  stage: deploy
  script:
    - docker stack deploy -c docker-compose.yml --with-registry-auth task
  only:
    - main
  tags:
    - prod
