language: ruby
rvm:
- 3.0.1
install:
  - bundle install
services:
  - postgresql
script:
  - bundle exec rails db:migrate:reset RAILS_ENV=test
  - bundle exec rspec
branches:
  only:
  - topic
  - main