language: ruby
rvm:
  - 3.0.1
install:
  - bundle install
services:
  - postgresql
script:
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - RAILS_ENV=test rails webpacker:compile
  - bundle exec rspec
branches:
  only:
  - topic
  - main
