version: '3'
networks:
  production:
volumes:
  db_data:
  gem_cache:
  shared_data:
  packs:

services:

  redis:
    image: redis:6.0-alpine
    command: redis-server
    networks:
      - production
    volumes:
      - shared_data:/var/shared/redis
    deploy:
      placement:
        constraints:
          - node.role == manager

  db:
    image: postgres:14-alpine
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - production
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    deploy:
      placement:
        constraints:
          - node.role == manager

  app:
    image: task_app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - production
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    command:
      # - rails assets:precompile
      - rails server -p 3000 -b 0.0.0.0
    # env_file: .env.example
    # environment:
      # RAILS_ENV: production
      # WEBPACKER_DEV_SERVER_HOST: webpacker
    depends_on:
      - db
      # - webpacker
    deploy:
      placement:
        constraints:
          - node.role == manager

  # webpacker:
    # image: task_app
    # build:
      # context: .
      # dockerfile: Dockerfile.dev
    # command: ruby bin/webpack-dev-server
    # volumes:
      # - shared_data:/var/shared
      # - gem_cache:/usr/local/bundle/gems
      # - .:/var/app
    # environment:
      # - NODE_OPTIONS=--max_old_space_size=4096
      # - NODE_ENV=production
      # - RAILS_ENV=production
      # - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    # ports:
      # - "3035:3035"
    # networks:
      # - production
    # deploy:
      # placement:
        # constraints:
          # - node.role == manager

  # visualizer:
    # image: dockersamples/visualizer:stable
    # ports:
      # - "8080:8080"
    # stop_grace_period: 1m30s
    # volumes:
      # - "/var/run/docker.sock:/var/run/docker.sock"
    # deploy:
      # placement:
        # constraints: [node.role == manager]

  # traefik:

