version: '3'
networks:
  net:
volumes:
  db_data:
  gem_cache:
  shared_data:

services:

  redis:
    image: redis:6.0-alpine
    command: redis-server
    networks:
      - net
    volumes:
      - shared_data:/var/shared/redis
    deploy:
      placement:
        constraints:
          - node.role == manager

  db:
    image: postgres:14-alpine
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    deploy:
      placement:
        constraints:
          - node.role == manager

  app:
    image: task_app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - net
    stdin_open: true
    # ports:
      # - 3000:3000
    tty: true
    # command:
      # - rails server -p 3000 -b 0.0.0.0
    env_file: .env
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - node.role == manager
