version: '3'
networks:
  net:
  traefik-public:
    external: true
volumes:
  db_data:
  gem_cache:
  shared_data:
  traefik-public-certificates:

services:

  redis:
    image: redis:6.0-alpine
    command: redis-server
    networks:
      - net
    volumes:
      - shared_data:/var/shared/redis
    deploy:
      placement:
        constraints:
          - node.role == manager

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - net
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    deploy:
      placement:
        constraints:
          - node.role == manager

  app:
    image: task_app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - net
      - traefik-public
    stdin_open: true
    # ports:
      # - 3000:3000
    tty: true
    # command:
      # - rails server -p 3000 -b 0.0.0.0
    env_file: .env
    depends_on:
      - postgres
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.task-http.rule=Host(`task.demo.jc713.staff.5xruby.dev`)
        - traefik.http.routers.task-http.entrypoints=http
        - traefik.http.routers.task-http.middlewares=https-redirect
        - traefik.http.routers.task-https.rule=Host(`task.demo.jc713.staff.5xruby.dev`)
        - traefik.http.routers.task-https.entrypoints=https
        - traefik.http.routers.task-https.tls=true
        - traefik.http.routers.task-https.tls.certresolver=le
        - traefik.http.services.task.loadbalancer.server.port=3000
        - traefik.http.routers.task-https.tls.domains[0].main=demo.jc713.staff.5xruby.dev
        - traefik.http.routers.task-https.tls.domains[0].sans=*.demo.jc713.staff.5xruby.dev
