version: '3.3'

volumes:
  traefik-public-certificates:

networks:
  traefik-public:
    external: true

services:

  traefik:
    image: traefik:v2.2
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    deploy:
      placement:
        constraints:
          - node.labels.traefik-public.traefik-public-certificates == true

      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # echo $(htpasswd -nb u pw) | sed -e s/\\$/\\$\\$/g
        - traefik.http.middlewares.admin-auth.basicauth.users=user:$$apr1$$gLsDEvPi$$Hci6ihq/g29IVGccseNpn1
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.traefik-public-http.rule=Host(`traefik.demo.jc713.staff.5xruby.dev`)
        - traefik.http.routers.traefik-public-http.entrypoints=http
        - traefik.http.routers.traefik-public-http.middlewares=https-redirect
        - traefik.http.routers.traefik-public-https.rule=Host(`traefik.demo.jc713.staff.5xruby.dev`)
        - traefik.http.routers.traefik-public-https.entrypoints=https
        - traefik.http.routers.traefik-public-https.tls=true
        - traefik.http.routers.traefik-public-https.service=api@internal
        - traefik.http.routers.traefik-public-https.tls.certresolver=le
        - traefik.http.routers.traefik-public-https.middlewares=admin-auth
        - traefik.http.routers.traefik-public-https.tls.domains[0].main=demo.jc713.staff.5xruby.dev
        - traefik.http.routers.traefik-public-https.tls.domains[0].sans=*.demo.jc713.staff.5xruby.dev
        - traefik.http.services.traefik-public.loadbalancer.server.port=8080


    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates

    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=joannachou713@5xruby.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.dnschallenge=true
      - --certificatesresolvers.le.acme.dnschallenge.provider=route53
      - --accesslog
      - --log.level=DEBUG
      - --api

    networks:
      - traefik-public

